/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DyteMeeting {
    }
}
declare global {
    interface HTMLDyteMeetingElement extends Components.DyteMeeting, HTMLStencilElement {
    }
    var HTMLDyteMeetingElement: {
        prototype: HTMLDyteMeetingElement;
        new (): HTMLDyteMeetingElement;
    };
    interface HTMLElementTagNameMap {
        "dyte-meeting": HTMLDyteMeetingElement;
    }
}
declare namespace LocalJSX {
    interface DyteMeeting {
    }
    interface IntrinsicElements {
        "dyte-meeting": DyteMeeting;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "dyte-meeting": LocalJSX.DyteMeeting & JSXBase.HTMLAttributes<HTMLDyteMeetingElement>;
        }
    }
}
