name: Pull Request Linter

on:
  pull_request:
    branches:
      - staging
      - main
    # By default, a workflow only runs when a pull_request's activity type is opened,
    # synchronize, or reopened. We explicity override here so that PR titles are re-linted when the PR text content is edited.
    types: [opened, edited, reopened]

jobs:
  pr-lint-title:
    runs-on: ubuntu-latest
    steps:
      - uses: morrisoncole/pr-lint-action@v1.6.1
        with:
          title-regex: "^(?<type>build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test|¯\\\\_\\(ツ\\)_\\/¯)(?<scope>\\(\\w+\\)?((?=:\\s)|(?=!:\\s)))?(?<breaking>!)?(?<subject>:\\s.*)?|^(?<merge>Merge \\w+)"
          on-failed-regex-fail-action: true
          on-failed-regex-request-changes: true
          on-failed-regex-create-review: true
          repo-token: "${{ secrets.GITHUB_TOKEN }}"

  pr-lint-body:
    runs-on: ubuntu-latest
    steps:
      - uses: dyte-in/pr-lint-body@main
        with:
          body-regex: "((close)|(closes)|(closed)|(closing)|(fix)|(fixes)|(fixed)|(fixing)|(resolve)|(resolves)|(resolved)|(resolving)|(complete)|(completes)|(completed)|(completing)) [A-Z]+-\\d+"
          body-regex-flags: "ig"
          on-failed-regex-fail-action: true
          on-failed-regex-request-changes: false
          on-failed-regex-create-review: false
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
