name: Release to NPM Registry
on:
  push:
    branches:
      - main
      - staging
      - props-less-uikit
  repository_dispatch:
    types: [prod-release]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: npm install

      - name: Build package
        run: npm run build

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
          ENVIRONMENT: ${{ github.ref }}
        run: npx semantic-release

      - name: Publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
        run: npx lerna exec -- npm publish --access public

      - name: Update staging branch
        if: |
          contains('refs/heads/main', github.ref)
        run: |
          git pull
          git stash
          git checkout staging
          git merge main
          git push --set-upstream origin staging
